from pydantic import BaseModel


class DTP(BaseModel):
    light: str
    region: str
    address: str
    category: str
    datetime: str
    severity: str
    dead_count: int
    injured_count: int
    parent_region: str
    participants_count: int
    point_x: float
    point_y: float
    tags2: int
    tags1: int
    tags0: int
    nearby11: int
    nearby33: int
    nearby43: int
    nearby36: int
    nearby51: int
    nearby12: int
    nearby6: int
    nearby22: int
    nearby24: int
    nearby42: int
    nearby60: int
    nearby44: int
    nearby14: int
    nearby8: int
    nearby61: int
    nearby19: int
    nearby30: int
    nearby54: int
    nearby4: int
    nearby13: int
    nearby37: int
    nearby29: int
    nearby17: int
    nearby58: int
    nearby38: int
    nearby31: int
    nearby2: int
    nearby32: int
    nearby28: int
    nearby16: int
    nearby20: int
    nearby27: int
    nearby40: int
    nearby48: int
    nearby5: int
    nearby34: int
    nearby41: int
    nearby9: int
    nearby57: int
    nearby26: int
    nearby55: int
    nearby10: int
    nearby49: int
    nearby56: int
    nearby45: int
    nearby7: int
    nearby46: int
    nearby39: int
    nearby59: int
    nearby21: int
    nearby1: int
    nearby50: int
    nearby53: int
    nearby52: int
    nearby3: int
    nearby0: int
    nearby25: int
    nearby47: int
    nearby18: int
    nearby15: int
    nearby35: int
    nearby23: int
    weather0: int
    weather1: int
    weather5: int
    weather4: int
    weather7: int
    weather6: int
    weather3: int
    weather8: int
    weather2: int
    road_conditions36: int
    road_conditions16: int
    road_conditions23: int
    road_conditions11: int
    road_conditions15: int
    road_conditions17: int
    road_conditions13: int
    road_conditions28: int
    road_conditions18: int
    road_conditions34: int
    road_conditions33: int
    road_conditions7: int
    road_conditions21: int
    road_conditions24: int
    road_conditions30: int
    road_conditions10: int
    road_conditions20: int
    road_conditions4: int
    road_conditions12: int
    road_conditions3: int
    road_conditions5: int
    road_conditions6: int
    road_conditions31: int
    road_conditions22: int
    road_conditions26: int
    road_conditions25: int
    road_conditions0: int
    road_conditions32: int
    road_conditions8: int
    road_conditions1: int
    road_conditions2: int
    road_conditions35: int
    road_conditions9: int
    road_conditions29: int
    road_conditions38: int
    road_conditions39: int
    road_conditions14: int
    road_conditions37: int
    road_conditions19: int
    road_conditions40: int
    road_conditions27: int
    participant_categories0: int
    participant_categories5: int
    participant_categories2: int
    participant_categories3: int
    participant_categories4: int
    participant_categories1: int

    # 'tags-2'
    # 'tags-1'
    # 'tags-0'
    # 'nearby-11'
    # 'nearby-33'
    # 'nearby-43'
    # 'nearby-36'
    # 'nearby-51'
    # 'nearby-12'
    # 'nearby-6'
    # 'nearby-22'
    # 'nearby-24'
    # 'nearby-42'
    # 'nearby-60'
    # 'nearby-44'
    # 'nearby-14'
    # 'nearby-8'
    # 'nearby-61'
    # 'nearby-19'
    # 'nearby-30'
    # 'nearby-54'
    # 'nearby-4'
    # 'nearby-13'
    # 'nearby-37'
    # 'nearby-29'
    # 'nearby-17'
    # 'nearby-58'
    # 'nearby-38'
    # 'nearby-31'
    # 'nearby-2'
    # 'nearby-32'
    # 'nearby-28'
    # 'nearby-16'
    # 'nearby-20'
    # 'nearby-27'
    # 'nearby-40'
    # 'nearby-48'
    # 'nearby-5'
    # 'nearby-34'
    # 'nearby-41'
    # 'nearby-9'
    # 'nearby-57'
    # 'nearby-26'
    # 'nearby-55'
    # 'nearby-10'
    # 'nearby-49'
    # 'nearby-56'
    # 'nearby-45'
    # 'nearby-7'
    # 'nearby-46'
    # 'nearby-39'
    # 'nearby-59'
    # 'nearby-21'
    # 'nearby-1'
    # 'nearby-50'
    # 'nearby-53'
    # 'nearby-52'
    # 'nearby-3'
    # 'nearby-0'
    # 'nearby-25'
    # 'nearby-47'
    # 'nearby-18'
    # 'nearby-15'
    # 'nearby-35'
    # 'nearby-23'
    # 'weather-0'
    # 'weather-1'
    # 'weather-5'
    # 'weather-4'
    # 'weather-7'
    # 'weather-6'
    # 'weather-3'
    # 'weather-8'
    # 'weather-2'
    # 'road_conditions-36'
    # 'road_conditions-16'
    # 'road_conditions-23'
    # 'road_conditions-11'
    # 'road_conditions-15'
    # 'road_conditions-17'
    # 'road_conditions-13'
    # 'road_conditions-28'
    # 'road_conditions-18'
    # 'road_conditions-34'
    # 'road_conditions-33'
    # 'road_conditions-7'
    # 'road_conditions-21'
    # 'road_conditions-24'
    # 'road_conditions-30'
    # 'road_conditions-10'
    # 'road_conditions-20'
    # 'road_conditions-4'
    # 'road_conditions-12'
    # 'road_conditions-3'
    # 'road_conditions-5'
    # 'road_conditions-6'
    # 'road_conditions-31'
    # 'road_conditions-22'
    # 'road_conditions-26'
    # 'road_conditions-25'
    # 'road_conditions-0'
    # 'road_conditions-32'
    # 'road_conditions-8'
    # 'road_conditions-1'
    # 'road_conditions-2'
    # 'road_conditions-35'
    # 'road_conditions-9'
    # 'road_conditions-29'
    # 'road_conditions-38'
    # 'road_conditions-39'
    # "road_conditions-14"
    # 'road_conditions-37'
    # 'road_conditions-19'
    # 'road_conditions-40'
    # "road_conditions-27"
    # "participant_categories-0"
    # "participant_categories-5"
    # 'participant_categories-2'
    # 'participant_categories-3'
    # 'participant_categories-4'
    # 'participant_categories-1'
